### ISSUE TITLE
dotmatrix

### ISSUE THREAD

**Issue by NatthawatTungruethaipak** [ioxhop/KidBright32_Arduino#1]
ข้อความ Hello World จะวิ่งจากซ้ายไปขวา ถ้าต้องการให้ข้อความ Hello World จะวิ่งจากขวาไปซ้ายต้องแก้ไขอย่างไรหรอครับ

**Comment by maxpromer** [comment]
หลักการของการวิ่ง คือการตั้งว่าให้ตัวอักษรแรกเริ่มต้นที่พิกัด x เท่าไร จากตัวอย่างโค้ดด้านล่างนี้ ตรง for จะกำหนดให้ตัวอักษณแรกเริ่มที่พิกัด x=16 แล้วจึงถอยเลขไปทีละ 1 เป็น 15 14 13 ... จนถึง -75 แล้วจึงจบการแสดงผล
```c++
  for (int8_t x = 16; x >= -75; x--) {
    matrix.clear();
    matrix.setCursor(x, 0);
    matrix.print("Hello World");
    matrix.writeDisplay();
    delay(100);
  }
```
ดังนั้น การแก้ให้วิ่งไปในทิศทางใด แก้จาก for ได้เลยครับ ตัวอย่างด้านล่างนี้คือวิ่ง x=-75 ไปจนถึง x=16 ครับ โดยสังเกตว่าจะแก้เฉพาะใน for เท่านั้นครับ
```c++
  for (int8_t x = -75 x <= 16; x++) {
    matrix.clear();
    matrix.setCursor(x, 0);
    matrix.print("Hello World");
    matrix.writeDisplay();
    delay(100);
  }
```
ขอแนะนำให้ท่านศึกษาโครงสร้างภาษา C เพิ่ม เรื่อง for loop ครับ

**Comment by NatthawatTungruethaipak** [comment]
ขอบพระคุณครับ
